const colors = {
  SkyBluePrimary: "#AFE3EF",
  DarkSkyBluePrimary: "#99D8E7",
  DarkSkyBlueBacking: "#8ECCDB",
  GreenPrimary: "#40CAA0",
  GreenBacking: "#38B38E",
  GreenText: "#4AA78B",
  GreenBacking2: "#4AA78B",
  LightBrown: "#FFF1E1",
  LightBrownBacking: "#D9C7B4",
  RegularBrown: "#F3C68E",
  RegularBrownBacking: "#C9A373",
  BrownText: "#9E6329",
  PurplePrimary: "#BF8EFF",
  PurpleBacking: "#A57CDA",
  WhiteText: "#FFFFFF",
  BlackText: "#282828",
  BlueText: "#13A4FF",
  BrightGreen: "#8EDE0F",
  BrightGreenBacking: "#79CB00",
  BluePrimary: "#68AFFF",
  BluePrimaryBacking: "#518ED2",
  WhiteBacking: "#D9D9D9",
  PrimaryRed: "#E6433A",
  GrayPrimary: "#ECECEC",
  GrayBacking: "#969696",
  PrimaryWhite: "#FFFFFF",
  BlueTint: "#DFEEFF",
  Disabled: "#959595",
  DisabledBacking: "#7D7E79",
  DisabledText: "#C8C9C4",
  LightBlue: "#DFEEFF",
  LightBlueBacking: "#C7DDF5",
  DarkBackground: "#282828",
  GrayButtonPrimary: "#959595",
  GrayButtonBacking: "#7E817A",
  AttackBacking: "#FE6B56",
  DefenseBacking: "#68AFFF",
  DarkGreenBacking: "#42987F",
} as const;

export type Colors = typeof colors; // Extract the type for the colors object
export default colors;
