import { StyleSheet } from "react-native";
import colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.DarkBackground,
    paddingVertical: 65,
    paddingHorizontal: 20,
    width: "100%",
    position: "relative",
  },
  centeredTextWrapper: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 40,
    padding: 20,
    width: "100%",
  },
  centeredWrapper: {
    position: "absolute",
    top: "35%",
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 40,
    padding: 20,
    width: "100%",
  },
  dustImageOne: {
    position: "absolute",
    width: 150,
    height: 150,
    top: 130,
    left: 40,
  },
  dustImageTwo: {
    position: "absolute",
    width: 150,
    height: 150,
    bottom: 130,
    right: 40,
    transform: [{ scaleX: -1 }, { scaleY: -1 }],
  },
  background: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 8,
    position: "relative",
  },
  sun: {
    width: 160,
    height: 160,
    position: "absolute",
    top: "9%",
    alignSelf: "center",
  },
  bottomWrapper: {
    position: "absolute",
    bottom: "7%",
    alignSelf: "center",
    width: "100%",
    padding: 20,
  },
  characterImage: {
    width: 140,
    height: 140,
    position: "absolute",
    top: "55%",
    right: "30%",
  },
  elephantImage: {
    width: 160,
    height: 160,
    position: "absolute",
    top: "55%",
    left: "1%",
  },
  giraffeImage: {
    width: 120,
    height: 120,
    position: "absolute",
    top: "30%",
    right: "1%",
    // transform: [{ scaleX: -1 }],
  },
  dolphinImage: {
    width: 100,
    height: 100,
    position: "absolute",
    bottom: "20%",
    right: "10%",
  },
  row: {
    alignItems: "center",
    width: "100%",
    position: "absolute",
    top: "6%",
    alignSelf: "center",
    flexDirection: "row",
    zIndex: 2,
    paddingLeft: 20,
  },
  backButton: {
    justifyContent: "center",
    alignItems: "center",
  },
  progressWrapper: {
    position: "absolute",
    left: "53%",
    transform: [{ translateX: -50 }],
  },
  progressCount: {
    borderRadius: 20,
    backgroundColor: colors.DarkSkyBlueBacking,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 30,
    paddingVertical: 6,
  },
});
